# lame_report/k8s-config.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lame-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lame-report
  template:
    metadata:
      labels:
        app: lame-report
    spec:
      containers:
      - name: lame-report
        image: lame_report:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lame-report
spec:
  selector:
    app: lame-report
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP